// env.js
const dotenv = require("dotenv");
dotenv.config();

const {
  NODE_ENV,
  COMMUNICATION_SERVICES_CONNECTION_STRING,
  AAD_CLIENT_ID,
  AAD_TENANT_ID,
  AAD_CLIENT_SECRET,
  SERVER_PORT,
  MSAL_USERNAME,
  MSAL_PASSWORD,
  TEAMS_CALLING_FEATURE_ID,
  // LOG_PERFORMANCE_METRICS,
} = process.env;
module.exports = {
  NODE_ENV,
  COMMUNICATION_SERVICES_CONNECTION_STRING,
  AAD_CLIENT_ID,
  AAD_TENANT_ID,
  AAD_CLIENT_SECRET,
  SERVER_PORT,
  MSAL_USERNAME,
  MSAL_PASSWORD,
  TEAMS_CALLING_FEATURE_ID,
  // LOG_PERFORMANCE_METRICS,
};
